funny_movie/config/routes.rb
Rails.application.routes.draw do
  get "videos/index"
  get "videos/new"
  get "videos/create"
  devise_for :users

  resources :videos, only: [:index, :new, :create]
  root to: "videos#index"


end

funny_movie/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

funny_movie/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :videos, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

funny_movie/app/models/video.rb
class Video < ApplicationRecord
    belongs_to :user
    validates :title,presence:true
    validates :url, presence:true, format: { with: /\Ahttps?:\/\/(www\.)?(youtube\.com|youtu\.be)\/.+\z/, message: "must be a valid YouTube URL" }
end

funny_movie/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

funny_movie/app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = current_user.videos.build(video_params)
    if @video.save
      redirect_to videos_path, notice: 'Video was successfully created.'
    else
      render :new
    end
  end
  def after_sign_out_path_for(resource_or_scope)
    videos_path 
  end

  private

  def video_params
    params.require(:video).permit(:title, :url)
  end
end

funny_movie/app/helpers/application_helper.rb
module ApplicationHelper
end

funny_movie/app/helpers/videos_helper.rb
module VideosHelper
end

funny_movie/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_include_tag 'theme_toggle' %>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <%= javascript_include_tag 'logout' %>
    
    <title><%= content_for(:title) || "Funny Movie" %></title>
    <%= stylesheet_link_tag 'style', media: 'all' %>
    <%= stylesheet_link_tag 'log', media: 'all' %>
    <%= stylesheet_link_tag 'register', media: 'all' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

funny_movie/app/views/videos/create.html.erb
<h1>Videos#create</h1>
<p>Find me in app/views/videos/create.html.erb</p>

funny_movie/app/views/videos/index.html.erb
<h1>Funny Movies</h1>
<div class="head">

  <%= link_to 'Share a new video', new_video_path %>

    <div class="outbutton"> 
    <% if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to 'Login', new_user_session_path %>
    <% end %>
      <button id="toggle-theme">
        <i class="fas fa-sun"></i>
      </button>
    </div>
</div>

<ul class="video-grid">
  <% @videos.each do |video| %>
    <li class="video-item">
      <h3>
        <%= video.title %>
         <% if video.user %>
          <span class="video-uploader">by <%= video.user.email %></span>
        <% end %>
      </h3>

      <% video_id = if video.url.include?('watch?v=') 
                      video.url.split('watch?v=').last.split('&').first 
                    elsif video.url.include?('youtu.be/') 
                      video.url.split('youtu.be/').last.split('&').first 
                    end %>

      <% video_url = "https://www.youtube.com/embed/#{video_id}" %>

      <iframe 
        src="<%= sanitize(video_url) %>" 
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
        allowfullscreen>
      </iframe>
    </li>
  <% end %>
</ul>

funny_movie/app/views/videos/new.html.erb
<h1>Share a New Video</h1>
<%= form_with model: @video, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>
  <div>
    <%= form.submit 'Share' %>
  </div>
<% end %>